### ISSUE TITLE
Problem pushing to repo

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly-docs-de#1]
Hi,

I've translated the Basic chapter, but cannot push to this repo after having checked it out and editing. How do we handle updates to the German documentation?

I have my editor set up to push to GitHub and have set user name and e-mail in my Git as well. I don't routinely use git, apologies if this is really basic noob stuff.

**Comment by danpros** [comment]
Hello,

Its fine. You need to fork it first and doing a pull request, read this page for more info https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

**Comment by danpros** [comment]
Great, already merge it and the web also updated https://docs.htmly.com/de/basic
